library(shiny)

ui <- fluidPage(
   #titlePanel('Information about Flights'),
   #tags$head(
    #tags$link(rel = "stylesheet", type = "text/css", href = "background.css")
   #),
   tags$head(
     tags$style(HTML("
      @import url('//fonts.googleapis.com/css?family=Lobster|Cabin:400,700');
      
      h1 {
        font-family: 'Lobster', cursive;
        font-weight: 500;
        line-height: 1;
        color: #ad1d28;
      }

    "))
   ),
  
   headerPanel("Information About Flights"),
    
    sidebarLayout(
      sidebarPanel(
        dateInput("date", 
                  h3("DATE"), 
                  value = '2018-04-28'),
        
        selectInput("select", h3("STARTING POINT"), 
                    choices = list(select = 'select any',
                                   "JFK - Newyork" = 1 , 
                                   "LAX - Los Angeles" = 2 ,
                                   "DFW - Dallas/Fort Worth International Airport" = 3  ,
                                   'OGG - Hawaii Kahului Airport'= 4 ,
                                   'HNL - Daniel K.Inouye International Airport' = 5 ,
                                   'SFO - San Francisco International Airport'= 6 ,
                                   'ATL - Hartsfield Jackson Atlanta International Airport' = 7,
                                   'BOS - Logan International Airport' = 8,
                                   'ONT - Ontario International Airport' = 9,
                                   'DCA - Ronald Reagan Washington National Airport' = 10 ,
                                   'LAS - McCarran International Airport' = 11 ,
                                   'IAD - Washington Dulles International Airport' =12 ,
                                   'JAX - Jacksonville International Airport' = 13,
                                   'MIA - Miami International Airport' = 14,
                                   'TPA - Tampa International Airport' = 15,
                                   'PHX - Phoenix Sky Harbor International Airport' =16 ,
                                   'PHL - Philadelphia International Airport' = 17,
                                   'SAN - San Diego International Airport' =18,
                                   'ORD - O Hare International Airport' = 19,
                                   'SEA - Seattle Tacoma International Airport' =20 ,
                                   'DTW - Detroit Metropolitan Airport' = 21,
                                   'SJC - San Jose International Airport' = 22,
                                   'SLC - Salt Lake City International Airport' =23 ,
                                   'KOA - Kona International Airport' = 24,
                                   'SJU - Luis MuÃ±oz MarÃn International Airport' =25 ,
                                   'MCO - Orlando International Airport' = 26,
                                   'DEN - Denver International Airport' = 27,
                                   'STL - St_Louis Lambert International Airport' = 28,
                                   'JAC - Jackson Hole Airport' = 29,
                                   'CLE - Cleveland Hopkins International Airport' = 30,
                                   'HOU - William P Hobby Airport' =31 ,
                                   'TUS - Tucson International Airport' = 32,
                                   'PDX - Portland International Airport' = 33,
                                   'IAH - George Bush Intercontinental Airport' = 34,
                                   'MSY - Louis Armstrong New Orleans International Airport' = 35 ,
                                   'SNA - John Wayne Airport' = 36,
                                   'BDL - Bradley International Airport' = 37,
                                   'RSW - Southwest Florida International Airport' = 38,
                                   'SAT - San Antonio International Airport' = 39,
                                   'MKE - General Mitchell International Airport' = 40 ,
                                   'PBI - Palm Beach Internationa Airport' = 41,
                                   'CLT - Charlotte Douglas International Airport' = 42 ,
                                   'BWI - Baltimore Washington International Airport' = 43,
                                   'LGA - LaGuardia Airport' = 44 ,
                                   'BNA - Nashville International Airport' = 45,
                                   'MFE - McAllen Miller International Airport' = 46,
                                   'EWR - Newark Liberty International Airport' = 47,
                                   'AUS - Austin Bergstrom International Airport' = 48,
                                   'RDU - Raleigh Durham International Airport' = 49,
                                   'LIH - Lihue Airport' = 50,
                                   'MCI - Crystal Airport' = 51,
                                   'ORF - Norfolk International Airport' =52,
                                   'COS - Colorado Springs Airport' = 53,
                                   'STT - Cyril E King Airport' = 54,
                                   'TUL - Tulsa International Airport' = 55,
                                   'FLL - Fort Lauderdale Hollywood International Airport' = 56,
                                   'IND - Indianapolis International Airport' = 57,
                                   'OKC - Will Rogers World Airport' = 58,
                                   'PIT - Pittsburgh International Airport' = 59,
                                   'ABQ - Albuquerque International Sunport Airport' = 60,
                                   'RNO - Reno Tahoe International Airport' = 61,
                                   'ABE - Lehigh Valley International Airport' = 62,
                                   'AGS - Augusta Regional Airport' = 63,
                                   'ALB - Albany International Airport' =64 ,
                                   'ANC - Ted Stevens Anchorage International Airport' =65,
                                   'ATW - Appleton International Airport' = 66,
                                   'AVL - AAsheville Regional Airport' = 67,
                                   'AVP - Wilkes Barre/Scranton International Airport' =68 ,
                                   'BGR - Bangor International Airport' = 69,
                                   'BHM - Birmingham Shuttlesworth International Airport' = 70,
                                   'BIL - Billings Logan International Airport' = 71,
                                   'BIS - Bismarck Municipal Airport' =72,
                                   'BOI - Boise Airport' = 73,
                                   'BQN - Rafael HernÃ¡ndez Airport' = 74,
                                   'BTR - Baton Rouge Metropolitan Airport' =75,
                                   'BTV - Burlington Internationa Airport' = 76,
                                   'BUF - Buffalo Niagara International Airport' =77 ,
                                   'BZN-Bozeman_Yellowstone_International_Airport' =78 ,
                                   'CAE-Columbia_Metropolitan_Airport' = 79,
                                   'CAK-Akron_Canton_Airport' = 80,
                                   'CHA-Chattanooga_Metropolitan_Airport1' = 81,
                                   'CHO-Charlottesville_Albemarle_Airport' = 82,
                                   'CHS-Charleston_International_Airport' = 83,
                                   'CMH-John_Glenn_Columbus_International_Airport' =84 ,
                                   'CRW-Yeager_Airport' = 85,
                                   'CVG-Cincinnati/Northern_Kentucky_International_Airport' = 86,
                                   'DAB-Daytona_Beach_International_Airport' = 87,
                                   'DAL-Dallas_Love_Field' = 88,
                                   'DAY-Dayton_International_Airport' = 89,
                                   'DLH-Duluth_International_Airport' = 90,
                                   'DSM-Des_Moines_International_Airport' = 91,
                                   'ECP-Northwest_Florida_Beaches_International_Airport' = 92,
                                   'EGE-Eagle_County_Regional_Airport' = 93,
                                   'ELP-El_Paso_International_Airport' = 94,
                                   'EVV-Evansville_Regional_Airport' = 95,
                                   'EYW-Key_West_International_Airport' = 96,
                                   'FAI-Fairbanks_International_Airport' = 97,
                                   'FAR-Hector_International_Airport' = 98,
                                   'FAT-Fresno_Yosemite_International_Airport' =99 ,
                                   'FAY-Fayetteville_Regional_Airport' = 100,
                                   'FCA-Glacier_Park_International_Airport' =101 ,
                                   'FNT-Bishop_International_Airport' = 102,
                                   'FSD-Sioux_Falls_Regional_Airport' = 103,
                                   'GEG-Spokane_International_Airport' = 104,
                                   'GNV-Gainesville_Regional_Airport' = 105,
                                   'GPT-Gulfport_Biloxi_International_Airport' = 106,
                                   'GRB-Green_Bay_Austin_Straubel_International_Airport' = 107,
                                   'GRR-Gerald_R_Ford_International_Airport' = 108,
                                   'GSO-Piedmont_Triad_International_Airport' = 109,
                                   'GSP-Greenville_Spartanburg_International_Airport' = 110,
                                   'GUC-Gunnison_Crested_Butte_Regional_Airport' = 111,
                                   'GUM-Antonio_B_Won_Pat_International_Airport' = 112,
                                   'HDN-Yampa_Valley_Airport' = 113,
                                   'HSV-Huntsville_International_Airport' = 114,
                                   'ICT-Wichita_Dwight_D_Eisenhower_National_Airport' = 115,
                                   'ILM-Wilmington_International_Airport' = 116,
                                   'ITO-Hilo_International_Airport' = 117,
                                   'JNU-Juneau_International_Airport' = 118, 
                                   'LBB-Lubbock_Preston_Smith_International_Airport' = 119,
                                   'LEX-Blue_Grass_Airport' = 120,
                                   'LFT-Lafayette_Regional_Airport' = 121,
                                   'LIT-Clinton_National_Airport' = 122,
                                   'LAN-Capital_Region_International_Airport' = 123,
                                   'MDT-Harrisburg_International_Airport' = 124,
                                   'MDW-Chicago_Midway_International_Airport' = 125,
                                   'MEM-Memphis_International_Airport' = 126,
                                   'MLB-Orlando_Melbourne_International_Airport' = 127,
                                   'MOB-Mobile_Regional_Airport' = 128,
                                   'MOT-Minot_International_Airport' = 129,
                                   'MSN-Dane_County_Regional_Airport' = 130,
                                   'MSO-Missoula_International_Airport' = 131,
                                   'MSP-Minneapolis_Saint_Paul_International_Airport' = 132,
                                   'MTJ-Montrose_Regional_Airport' = 133,
                                   'MYR-Myrtle_Beach_International_Airport' = 134,
                                   'OAK-Oakland_International_Airport' = 135,
                                   'OMA-Eppley_Airfield' = 136,
                                   'PHF-Newport_News/Williamsburg_International_Airport' =137 ,
                                   'PNS-Pensacola_International_Airport' = 138,
                                   'PSC-Tri_Cities_Airport' = 139,
                                   'PSP-Palm_Springs_International_Airport' =140 ,
                                   'PVD-T_F_Green_Airport' = 141,
                                   'PWM-Portland_International_Jetport' =142 ,
                                   'RAP-Rapid_City_Regional_Airport' = 143,
                                   'RIC-Richmond_International_Airport' = 144,
                                   'ROA-Roanoke_Blacksburg_Regional_Airport' = 145,
                                   'ROC-Greater_Rochester_International_Airport' = 146,
                                   'SAV-Savannah/Hilton_Head_International_Airport' = 147,
                                   'SDF-Louisville_International_Airport' =148,
                                   'SGF-Springfield_Branson_National_Airport' =149 ,
                                   'SHV-Shreveport_Regional_Airport' = 150,
                                   'SMF-Sacramento_International_Airport' =151 ,
                                   'SRQ-Sarasota_Bradenton_International_Airport' =152 ,
                                   'STX-Henry_E_Rohlsen_Airport' = 153,
                                   'SYR-Syracuse_Hancock_International_Airport' =154 ,
                                   'TLH-Tallahassee_International_Airport' = 155,
                                   'TRI-Tri_Cities_Regional_Airport' = 156,
                                   'TVC-Cherry_Capital_Airport' = 157,
                                   'TYS-McGhee_Tyson_Airport' = 158,
                                   'VPS-Northwest_Florida_Regional_Airport' = 159,
                                   'XNA-Northwest_Arkansas_Regional_Airport' = 160
                    )),
        
        selectInput("select", h3("DESTINATION"), 
                    choices = list(select = 'select any',
                                   "JFK - Newyork" = 1 , 
                                   "LAX - Los_Angeles" = 2 ,
                                   "DFW - Dallas/Fort_Worth_International_Airport" = 3  ,
                                   'OGG - Hawaii_Kahului_Airport'= 4 ,
                                   'HNL - Daniel_K._Inouye_International_Airport' = 5 ,
                                   'SFO-San_Francisco_International_Airport'= 6 ,
                                   'ATL-Hartsfield_Jackson_Atlanta_International_Airport' = 7,
                                   'BOS-Logan_International_Airport' = 8,
                                   'ONT-Ontario_International_Airport' = 9,
                                   'DCA-Ronald_Reagan_Washington_National_Airport' = 10 ,
                                   'LAS-McCarran_International_Airport' = 11 ,
                                   'IAD-Washington_Dulles_International_Airport' =12 ,
                                   'JAX-Jacksonville_International_Airport' = 13,
                                   'MIA-Miami_International_Airport' = 14,
                                   'TPA-Tampa_International_Airport' = 15,
                                   'PHX-Phoenix_Sky_Harbor_International_Airport' =16 ,
                                   'PHL-Philadelphia_International_Airport' = 17,
                                   ' SAN-San_Diego_International_Airport' =18,
                                   'ORD-O_Hare_International_Airport' = 19,
                                   'SEA-Seattle_Tacoma_International_Airport' =20 ,
                                   'DTW-Detroit_Metropolitan_Airport' = 21,
                                   'SJC-San_Jose_International_Airport' = 22,
                                   'SLC-Salt_Lake_City_International_Airport' =23 ,
                                   'KOA-Kona_International_Airport' = 24,
                                   'SJU-Luis_MuÃoz_MarÃn_International_Airport' =25 ,
                                   'MCO-Orlando_International_Airport' = 26,
                                   'DEN-Denver_International_Airport' = 27,
                                   'STL-St_Louis_Lambert_International_Airport' = 28,
                                   'JAC-Jackson_Hole_Airport' = 29,
                                   'CLE-Cleveland_Hopkins_International_Airport' = 30,
                                   'HOU-William_P_Hobby_Airport' =31 ,
                                   'TUS-Tucson_International_Airport' = 32,
                                   'PDX-Portland_International_Airport' = 33,
                                   'IAH-George_Bush_Intercontinental_Airport' = 34,
                                   'MSY-Louis_Armstrong_New_Orleans_International_Airport' = 35 ,
                                   'SNA-John_Wayne_Airport' = 36,
                                   'BDL-Bradley_International_Airport' = 37,
                                   'RSW-Southwest_Florida_International_Airport' = 38,
                                   'SAT-San_Antonio_International_Airport' = 39,
                                   'MKE-General_Mitchell_International_Airport' = 40 ,
                                   'PBI-Palm_Beach_Internationa_Airport' = 41,
                                   'CLT-Charlotte_Douglas_International_Airport' = 42 ,
                                   'BWI-Baltimore_Washington_International_Airport' = 43,
                                   'LGA-LaGuardia_Airport' = 44 ,
                                   'BNA-Nashville_International_Airport' = 45,
                                   'MFE-McAllen_Miller_International_Airport' = 46,
                                   'EWR-Newark_Liberty_International_Airport' = 47,
                                   'AUS-Austin_Bergstrom_International_Airport' = 48,
                                   'RDU-Raleigh_Durham_International_Airport' = 49,
                                   'LIH-Lihue_Airport' = 50,
                                   'MCI-Crystal_Airport' = 51,
                                   'ORF-Norfolk_International_Airport' =52,
                                   'COS-Colorado_Springs_Airport' = 53,
                                   'STT-Cyril_E_King_Airport' = 54,
                                   'TUL-Tulsa_International_Airport' = 55,
                                   'FLL-Fort_Lauderdale_Hollywood_International_Airport' = 56,
                                   'IND-Indianapolis_International_Airport' = 57,
                                   'OKC-Will_Rogers_World_Airport' = 58,
                                   'PIT-Pittsburgh_International_Airport' = 59,
                                   'ABQ-Albuquerque_International_Sunport_Airport' = 60,
                                   'RNO-Reno_Tahoe_International_Airport' = 61,
                                   'ABE-Lehigh_Valley_International_Airport' = 62,
                                   'AGS-Augusta_Regional_Airport' = 63,
                                   'ALB-Albany_International_Airport' =64 ,
                                   ' ANC-Ted_Stevens_Anchorage_International_Airport' =65,
                                   'ATW-Appleton_International_Airport' = 66,
                                   'AVL-AAsheville_Regional_Airport' = 67,
                                   'AVP-Wilkes_Barre/Scranton_International_Airport' =68 ,
                                   'BGR-Bangor_International_Airport' = 69,
                                   'BHM-Birmingham_Shuttlesworth_International_Airport' = 70,
                                   'BIL-Billings_Logan_International_Airport' = 71,
                                   'BIS-Bismarck_Municipal_Airport' =72,
                                   'BOI-Boise_Airport' = 73,
                                   'BQN-Rafael_HernÃ¡ndez_Airport' = 74,
                                   'BTR-Baton_Rouge_Metropolitan_Airport' =75,
                                   'BTV-Burlington_Internationa_Airport' = 76,
                                   'BUF-Buffalo_Niagara_International_Airport' =77 ,
                                   'BZN-Bozeman_Yellowstone_International_Airport' =78 ,
                                   'CAE-Columbia_Metropolitan_Airport' = 79,
                                   'CAK-Akron_Canton_Airport' = 80,
                                   'CHA-Chattanooga_Metropolitan_Airport1' = 81,
                                   'CHO-Charlottesville_Albemarle_Airport' = 82,
                                   'CHS-Charleston_International_Airport' = 83,
                                   'CMH-John_Glenn_Columbus_International_Airport' =84 ,
                                   'CRW-Yeager_Airport' = 85,
                                   'CVG-Cincinnati/Northern_Kentucky_International_Airport' = 86,
                                   'DAB-Daytona_Beach_International_Airport' = 87,
                                   'DAL-Dallas_Love_Field' = 88,
                                   'DAY-Dayton_International_Airport' = 89,
                                   'DLH-Duluth_International_Airport' = 90,
                                   'DSM-Des_Moines_International_Airport' = 91,
                                   'ECP-Northwest_Florida_Beaches_International_Airport' = 92,
                                   'EGE-Eagle_County_Regional_Airport' = 93,
                                   'ELP-El_Paso_International_Airport' = 94,
                                   'EVV-Evansville_Regional_Airport' = 95,
                                   'EYW-Key_West_International_Airport' = 96,
                                   'FAI-Fairbanks_International_Airport' = 97,
                                   'FAR-Hector_International_Airport' = 98,
                                   'FAT-Fresno_Yosemite_International_Airport' =99 ,
                                   'FAY-Fayetteville_Regional_Airport' = 100,
                                   'FCA-Glacier_Park_International_Airport' =101 ,
                                   'FNT-Bishop_International_Airport' = 102,
                                   'FSD-Sioux_Falls_Regional_Airport' = 103,
                                   'GEG-Spokane_International_Airport' = 104,
                                   'GNV-Gainesville_Regional_Airport' = 105,
                                   'GPT-Gulfport_Biloxi_International_Airport' = 106,
                                   'GRB-Green_Bay_Austin_Straubel_International_Airport' = 107,
                                   'GRR-Gerald_R_Ford_International_Airport' = 108,
                                   'GSO-Piedmont_Triad_International_Airport' = 109,
                                   'GSP-Greenville_Spartanburg_International_Airport' = 110,
                                   'GUC-Gunnison_Crested_Butte_Regional_Airport' = 111,
                                   'GUM-Antonio_B_Won_Pat_International_Airport' = 112,
                                   'HDN-Yampa_Valley_Airport' = 113,
                                   'HSV-Huntsville_International_Airport' = 114,
                                   'ICT-Wichita_Dwight_D_Eisenhower_National_Airport' = 115,
                                   'ILM-Wilmington_International_Airport' = 116,
                                   'ITO-Hilo_International_Airport' = 117,
                                   'JNU-Juneau_International_Airport' = 118, 
                                   'LBB-Lubbock_Preston_Smith_International_Airport' = 119,
                                   'LEX-Blue_Grass_Airport' = 120,
                                   'LFT-Lafayette_Regional_Airport' = 121,
                                   'LIT-Clinton_National_Airport' = 122,
                                   'LAN-Capital_Region_International_Airport' = 123,
                                   'MDT-Harrisburg_International_Airport' = 124,
                                   'MDW-Chicago_Midway_International_Airport' = 125,
                                   'MEM-Memphis_International_Airport' = 126,
                                   'MLB-Orlando_Melbourne_International_Airport' = 127,
                                   'MOB-Mobile_Regional_Airport' = 128,
                                   'MOT-Minot_International_Airport' = 129,
                                   'MSN-Dane_County_Regional_Airport' = 130,
                                   'MSO-Missoula_International_Airport' = 131,
                                   'MSP-Minneapolis_Saint_Paul_International_Airport' = 132,
                                   'MTJ-Montrose_Regional_Airport' = 133,
                                   'MYR-Myrtle_Beach_International_Airport' = 134,
                                   'OAK-Oakland_International_Airport' = 135,
                                   'OMA-Eppley_Airfield' = 136,
                                   'PHF-Newport_News/Williamsburg_International_Airport' =137 ,
                                   'PNS-Pensacola_International_Airport' = 138,
                                   'PSC-Tri_Cities_Airport' = 139,
                                   'PSP-Palm_Springs_International_Airport' =140 ,
                                   'PVD-T_F_Green_Airport' = 141,
                                   'PWM-Portland_International_Jetport' =142 ,
                                   'RAP-Rapid_City_Regional_Airport' = 143,
                                   'RIC-Richmond_International_Airport' = 144,
                                   'ROA-Roanoke_Blacksburg_Regional_Airport' = 145,
                                   'ROC-Greater_Rochester_International_Airport' = 146,
                                   'SAV-Savannah/Hilton_Head_International_Airport' = 147,
                                   'SDF-Louisville_International_Airport' =148,
                                   'SGF-Springfield_Branson_National_Airport' =149 ,
                                   'SHV-Shreveport_Regional_Airport' = 150,
                                   'SMF-Sacramento_International_Airport' =151 ,
                                   'SRQ-Sarasota_Bradenton_International_Airport' =152 ,
                                   'STX-Henry_E_Rohlsen_Airport' = 153,
                                   'SYR-Syracuse_Hancock_International_Airport' =154 ,
                                   'TLH-Tallahassee_International_Airport' = 155,
                                   'TRI-Tri_Cities_Regional_Airport' = 156,
                                   'TVC-Cherry_Capital_Airport' = 157,
                                   'TYS-McGhee_Tyson_Airport' = 158,
                                   'VPS-Northwest_Florida_Regional_Airport' = 159,
                                   'XNA-Northwest_Arkansas_Regional_Airport' = 160
                                   
                    ))
        
      ),
      
      mainPanel()
    )
  )
  
  
  server <- function(input,output){
    
  }
  
  shinyApp(ui=ui,server=server)
  
